# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:ios)

platform :ios do
  desc "Setup the iOS app"
  lane :setup do 
    # XCode setup
    bundle_install

    # Pods setup
    cocoapods

    # Config
    content = load_json(json_path: "config.json")
    update_project_team(
      path: "iOS-Template.xcodeproj",
      teamid: content["teamid"]
    )
  end

  desc "Take screenshots of the app"
  lane :screenshot do
    snapshot
    frameit
  end

  desc "Deploy a test to testflight"
  lane :test do 
    increment_build_number
    gym
    pilot
    UI.message("Newest testflight build: " + latest_testflight_build_number)
  end

  desc "Check for errors"
  lane :error do 
    swiftlint
    content = load_json(json_path: "config.json")
    scan
  end

  desc "Create documentation"
  lane :documentation do 
    appledoc
  end

  desc "Deploy app to appstore"
  lane :deploy do
    increment_build_number
    precheck
    gym
    deliver(precheck_default_rule_level: :error)
  end
end

